spring:
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/location}
        username: ${SPRING_DATASOURCE_USERNAME:location}
        password: ${SPRING_DATASOURCE_PASSWORD:fitiz-location}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
server:
    port: 5000